docker-deploy/web-app/rideapp/urls.py
from django.contrib import admin
from django.urls import include, path
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name='home'),
    
]

docker-deploy/web-app/user/urls.py
from django.urls import path, include
from django.contrib import admin 

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('driver_site/', views.driver_site, name='driver_site'),
    path('register/', views.register, name='register'),
    # path('login/', views.login, name='login'),
    path('start_request/', views.start_request, name='start_request'),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('request_detail/<int:nid>/', views.request_detail, name='request_detail'),
    path('<int:nid>/edit_request/', views.edit_request, name='edit_request'),
    path('<int:nid>/delete_request/', views.delete_request, name='delete_request'),
    path('search_ride/', views.search_ride, name='search_ride'),
    path('join_request/<int:nid>/<int:num>', views.join_request, name='join_request'),
    path('quit_request/<int:nid>/', views.quit_request, name='quit_request'),
    path('driver_register/', views.driver_register, name='driver_register'),
    path('driver_unregister/', views.driver_unregister, name='driver_unregister'),
    path('driver_search/', views.driver_search, name='driver_search'),
     path('driver_order/', views.driver_order, name='driver_order'),
    path('<int:ride_id>/complete_order/', views.complete_order, name='complete_order'),
    # path('order_detail/<int:ride_id>/', views.order_detail, name='order_detail'),
    path('driver_confirm/<int:ride_id>/', views.driver_confirm, name='driver_confirm'),
     path('user_info/', views.user_info, name='user_info'),
    
]

docker-deploy/web-app/user/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
# from django.contrib.postgres.fields import DictionaryField
# Create your models here.

class ThingPriority(models.IntegerChoices):
    Sedan = 4, 'Sedan'
    Coupe = 3, 'Coupe'
    SUV = 5, 'SUV'
    Pickup = 6, 'Pickup'



class Driver(models.Model):
    user = models.OneToOneField(User, related_name='driver2_user_set', on_delete=models.CASCADE)
    vehicle_type = models.IntegerField(verbose_name="Vehicle Type",choices=ThingPriority.choices)
    plate_num = models.CharField(max_length=256,null=True,blank=True)
    capacity = models.IntegerField(validators=[MinValueValidator(1)],null=True,blank=True)
    special_vehicle_info = models.TextField(max_length=256,null=True,blank=True)

class Ride(models.Model):
    id = models.BigAutoField(primary_key=True)
    destination = models.CharField(max_length=256)
    arrival_time = models.DateTimeField(default=timezone.now)
    passenger_number = models.IntegerField(validators=[
            MinValueValidator(1)
        ])
    owner = models.ForeignKey(User, on_delete=models.CASCADE,related_name='owner_user_set',blank=True,null=True)
    driver = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True,related_name='driver_user_set')
    is_shared = models.BooleanField(default=False)
    sharer = models.ManyToManyField(User,related_name="sharer",blank=True)
    status_option= {
        ('Open','Open'),
        ('Confirmed','Confirmed'),
        ('Completed','Completed')
    }
    status = models.CharField(max_length=32, choices=status_option, default="Open")

    special_request = models.CharField(max_length=256,blank=True,default='')
    # vehicle = {
    #     (4, 'Sedan'),
    #     (5, 'SUV'),
    #     (6, 'Pickup'),
    #     (4, 'Coupe')
    # }
    special_vehicle_type = models.IntegerField(verbose_name="special_vehicle_type", choices=ThingPriority.choices, blank=True, null=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)
    
    class Meta:
        #(permission_code, human_readable_permission_name).
        permissions = (
            ("is_driver", "is_driver"),
        )
    

class RideSharer(models.Model):
    user_sharer = models.ForeignKey(User, related_name="user_share", on_delete=models.CASCADE)
    passenger_num = models.IntegerField(validators=[MinValueValidator(1)])
    joined_ride = models.ForeignKey(Ride, related_name="joinedride", on_delete=models.CASCADE)

docker-deploy/web-app/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Ride, Driver
from django.contrib.auth.models import User, Permission
from datetime import datetime, timedelta, tzinfo
from django.utils import timezone


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    #is_driver = forms.BooleanField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class RegisterForm(ModelForm):
    class Meta: 
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class StartRequestForm(ModelForm):
    class Meta:
        model = Ride
        fields = ['destination', 'arrival_time', 'passenger_number', 'is_shared', 'special_vehicle_type' ,'special_request' ]

class EditRequestForm(ModelForm):
    class Meta:
        model = Ride
        fields = ['destination', 'arrival_time', 'passenger_number', 'is_shared', 'special_vehicle_type' ,'special_request' ]



class JoinRequestForm(ModelForm):
    earliest_time = forms.DateTimeField(initial=timezone.now)
    latest_time = forms.DateTimeField(initial=timezone.now)

    class Meta:
        model = Ride
        fields = ['destination', 'passenger_number', 'special_vehicle_type', 'special_request', 'earliest_time', 'latest_time']


class DriverRideForm(forms.ModelForm):
    class Meta:
        model = Ride
        fields = ['destination', 'arrival_time',
        'passenger_number', 'owner', 'driver', 'is_shared', 'sharer',
        'status', 'special_request', 'special_vehicle_type']
    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class" : "form-control", "placeholder": field.label}

class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class" : "form-control", "placeholder": field.label}

docker-deploy/web-app/user/views.py
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import Ride, Driver, RideSharer
from django.core.mail import send_mass_mail,BadHeaderError
from django.contrib.auth.models import User, Permission 
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from .forms import  StartRequestForm, JoinRequestForm, EditRequestForm, UserRegisterForm
from django.urls import reverse
from django import forms
from django.db.models import F
from django.core.mail import send_mass_mail,BadHeaderError
# # Create your views here.



@login_required
def home(request):
    # Render the HTML template index.html with the data in the context variable
    if request.user.is_authenticated:
        #print(request.user)
        orders_owner = list(Ride.objects.filter(owner=request.user))
        orders_sharer = list(Ride.objects.filter(sharer = request.user))
        context = {
            'orders_owner': orders_owner,
            'orders_sharer': orders_sharer
        }
    else:
        context = {}
    return render(request, 'user/home.html', context)





# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            
            new_user = form.cleaned_data['username']
            new_email = form.cleaned_data.get('email')
            user_existed = User.objects.filter(username = new_user)
            print(new_user)
            if user_existed:
                msg = "username has been used!"
                return render(request, 'user/register.html', {'message': msg})
            email_existed = User.objects.filter(email = new_email)
            if email_existed:
                msg = "email has been used!"
                return render(request, 'user/register.html', {'message': msg})


            form.save()
            msg = "Your account has been created! You are now able to log in!"
            # 
            return render(request, 'user/home.html', {'message':msg})
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form':form})



@login_required
def start_request(request):
    if request.method == 'POST':
        form = StartRequestForm(request.POST)
        if form.is_valid():
            # print(request.user)
            #need to check if orders have time overlap -- which is unaccepted!!

            ride = form.save()
            ride.owner = request.user
            ride.save()
            # username = form.cleaned_data.get('username')
            # messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('home')
    else:
        form = StartRequestForm()
    return render(request, 'user/start_request.html', {'form':form})

@login_required
def user_order(request):
    own_orders = list(Ride.objects.filter(owner=request.user))
    share_orders = list(Ride.objects.filter(sharer = request.user))
    context = {
        'ride_own': own_orders, 
        'ride_share' : share_orders
    }
    return render(request, 'user/home.html', context)

@login_required
def edit_request(request, nid):
    obj = Ride.objects.filter(id=nid).first()
    if obj.status!="Open":
        msg = "Order confirmed, can't make changes"
        return render(request, 'user/index.html', {"message":msg})
    if request.method == "GET":
        form = EditRequestForm(instance = obj)
        return render(request, 'user/edit_request.html', {"form": form})
    form = EditRequestForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('home')
    return render(request, 'user/edit_request.html', {"form": form})

def delete_request(request, nid):
    ride = Ride.objects.filter(id=nid).first()
    if ride.status!="Open":
        msg = "Order confirmed, can't make changes"
        return render(request, 'user/index.html', {"message":msg})
    Ride.objects.filter(id=nid).first().delete()
    return redirect('home')

def request_detail(request, nid):
    ride = Ride.objects.filter(id=nid).first()
    context = {
        'ride': ride
    }
    return render(request, 'user/request_detail.html', context)

@login_required
def join_request(request, nid, num):
    # this is a GET method

    Ride.objects.filter(id=nid).update(passenger_number=F('passenger_number') + num)
    ride = Ride.objects.filter(id=nid).first()
    ride.sharer.add(request.user)
    # sharer_list = ride.sharer_number_list
    # sharer_list[request.user.get_uesrname()] = num
    ride.save()
    sharer = RideSharer.objects.create(user_sharer=request.user, passenger_num=num,joined_ride=ride)
    return redirect('home')

@login_required
def quit_request(request, nid):
    ride = Ride.objects.filter(id=nid).first()
    if ride.status!="Open":
        msg = "Order confirmed, can't make changes"
        return render(request, 'user/index.html', {"message":msg})
    sharer = RideSharer.objects.filter(joined_ride=ride).filter(user_sharer=request.user).first()
    num = sharer.passenger_num
    Ride.objects.filter(id=nid).first().sharer.remove(request.user)
    Ride.objects.filter(id=nid).update(passenger_number=F('passenger_number') - num)
    # Ride.objects.filter(id=nid).first().update(passenger_number=F('passenger_number') - num)
    return redirect('home')

@login_required
def search_ride(request):
    if request.method == "POST":
        form = JoinRequestForm(request.POST)
        if form.is_valid():
            #!!! to be added: need to check if orders have time overlap -- which is unaccepted!!

             
            ans = Ride.objects.filter(status="Open").filter(is_shared=True)
            ans = ans.exclude(owner__exact=request.user).exclude(sharer__exact=request.user)
            # 1. sharer has a special vehicle type request
            if (form.cleaned_data['special_vehicle_type'] != None):               
                ans = ans.filter(special_vehicle_type__exact=form.cleaned_data['special_vehicle_type']).filter(special_vehicle_type__gte= F('passenger_number')+form.cleaned_data['passenger_number'])
            # 2. sharer does not have a special vehicle type request
            else:
                ans_not_special = ans.filter(special_vehicle_type=None).filter(passenger_number__lte=6-form.cleaned_data['passenger_number'])
                ans_special = ans.filter(special_vehicle_type__gte= F('passenger_number')+form.cleaned_data['passenger_number'])
                ans = ans_special | ans_not_special
            ans = ans.filter(destination__exact=form.cleaned_data['destination'])
            ans = ans.filter(arrival_time__gte = form.cleaned_data['earliest_time']).filter(arrival_time__lte = form.cleaned_data['latest_time'])

            context = {
                'ans': ans,
                'num': form.cleaned_data['passenger_number']
            }
            # username = form.cleaned_data.get('username')
            # messages.success(request, f'Your account has been created! You are now able to log in')
            return render(request, 'user/show_available_ride.html', context)
    else:
        form = JoinRequestForm()
    return render(request, 'user/search_ride.html', {'form':form})



@login_required
def driver_register(req):
    user = req.user
    if Driver.objects.filter(user_id=user.id).count()>0:
        msg = "You have already registered as a driver!"
        return render(req, 'user/index.html', {'message': msg})
    if req.method == "GET":
        return render(req, 'user/driver_register.html')
    received_data = req.POST
    #print(received_data.get("capacity"))
    vehicle_type=received_data.get("vehicle")
    plate_num=received_data.get("plate")
    plate_existed = Driver.objects.filter(plate_num = plate_num)
    if plate_existed:
        msg = "Plate number already registered!"
        return render(req, 'user/driver_register.html', {'message': msg})
    driver = Driver.objects.create(user=req.user, 
                    vehicle_type=received_data.get("vehicle"),
                    plate_num=received_data.get("plate"),
                    capacity= vehicle_type,
                    special_vehicle_info=received_data.get("special_info"))
    
    perm = Permission.objects.get(codename='is_driver')
    user.user_permissions.add(perm) 
    print(user.has_perm('user.is_driver'))
    driver.save()
    user.save()
    msg = "Great, you are a driver now!"
    return redirect('driver_site')

@login_required
def user_info(req):
    user = req.user
    is_driver = Driver.objects.filter(user_id=user.id).count()
    if req.method == "GET":
        driver_info = None
        plate_type = None
        if Driver.objects.filter(user_id=user.id).count() > 0:
            driver_info = Driver.objects.get(user=req.user)
            plate_type = driver_info.get_vehicle_type_display()
        username = User.objects.get(username=req.user).username
        email = User.objects.get(username=req.user).email
        context = {
            'username':username, 
            'email':email,
            'is_driver':is_driver,
            'plate_type':plate_type
        }
        return render(req, 'user/user_info.html', {'driver': driver_info,'context':context})
    data = req.POST
    if Driver.objects.filter(user_id=user.id).count() > 0:
        driver_info = Driver.objects.get(user=user)
        driver_info.plate_num = data.get("plate")
        if data.get("vehicle_type")!=None:
            driver_info.vehicle_type = data.get("vehicle_type")
            driver_info.capacity = driver_info.vehicle_type
        driver_info.special_vehicle_info = data.get("vehicle_info")
        print(driver_info.get_vehicle_type_display())
        driver_info.save()
    user_info = User.objects.get(username=user)
    user_info.username = data['name']

docker-deploy/web-app/user/templates/user/complete_order.html
{% extends "user/driver_site2.html" %}

{% block content %}
   {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
{% endblock%}

docker-deploy/web-app/user/templates/user/driver_confirm.html
{% extends "user/driver_site2.html" %}

{% block content %}
   <h1>Driver Confirm</h1>
   <p><a href="{% url 'driver_site' %}">Back</a></p> 
   <form action="{% url 'driver_confirm'  %}" method="post">
               <tr>
                <th>Destination</th> 
                <th>Arrival_time</th>  
                <th>Passenger_number</th>  
                <th>Owner</th>  
                <th>Vehicle_type</th>  
                <th>Status</th><br>  
            </tr>
    {% csrf_token %}
        {% for obj in rides %}
            <tr> 
                <th>{{obj.destination.label}}: {{obj.destination}}</th>
                <th>{{obj.arrival_time.label}} {{obj.arrival_time}}</th>  
                <th>{{obj.passenger_number.label}} {{obj.passenger_number}}</th>  
                <th>{{obj.owner.label}} {{obj.owner}}</th>  
                <th>{{obj.special_vehicle_type.label}} {{obj.special_vehicle_type}}</th>  
                <th>{{obj.status.label}} {{obj.status}}</th> 
                <a  type="submit" class="btn cbtn" href="{% url 'driver_confirm' obj.id %}" >Claim</a> <hr>
            </tr>
        {% endfor%}
   {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
   </form>
{% endblock%}

docker-deploy/web-app/user/templates/user/driver_order.html
{% extends "user/driver_site2.html" %}

{% block content %}
   <h3 class="text-center">My Confirmed Orders</h3>


    <div class="container">
        <div>
  
        </div>
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          </div>
  
          <!-- Table -->
        <table class="table table-bordered">
            <thead>
              <tr>
                <th>Ride Destination</th>
                <th>Arrival Time</th>
                <th>Order Owner</th>
                <th>Current Status</th>
              </tr>
            </thead>
            <tbody>
              {% for obj in rides %}
              {% if obj.status != "Completed" %}
              <tr>
                <!-- <th scope="row">1</th> -->
                <td>{{obj.destination}}</td>
                <td>{{obj.arrival_time}}</td>
                <td>{{obj.owner}}</td>
                <td>{{obj.status}}</td>
                <td>
                  <a style="color:white" class="btn btn-secondary btn-xs"
                    href="{% url 'request_detail' obj.id %}">Details</a>
                  <a style="color:white" class="btn btn-success btn-xs" href="{% url 'complete_order' obj.id %}">Complete</a>
                  <!-- <button class="btn btn-primary" type="button">Button</button>
                  <button class="btn btn-primary" type="button">Button</button> -->
                </td>
              </tr>
              {% endif %}
              {% endfor %}
            </tbody>
        </table>
  


{% endblock%}

docker-deploy/web-app/user/templates/user/driver_register.html
{% extends "user/home.html" %}
{% block content %}
   <h1 class="text-center">Driver Register</h1>
   <div class="container">
    <div class="panel panel-default">
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}

                <div class="form-group">
                    <label>Choose a vehicle type:</label>
                    <select class="form-control" name="vehicle">
                        <option value="4">Sedan - up to 4 Passengers</option>
                        <option value="5">SUV - up to 5 Passengers</option>
                        <option value="6">Pickup - up to 6 Passengers</option>
                        <option value="3">Coupe - - up to 3 Passengers</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Plate number:</label>
                    <input type="text" class="form-control" name="plate" required pattern="[A-Z0-9]{0,10}">
                </div>
                <div class="form-group">
                    <label>Special vehicle info:</label>
                    <input type="text" class="form-control" name="special_info" >
                </div>

                <div class="form-group">
                    <button class="btn btn-success btn-xs" type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div class="border-top pt-3">
            <small class="text-center ">
                Already Have A Driver Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
</div>
                <div class="text-center">
   {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
                </div>

{% endblock %}

docker-deploy/web-app/user/templates/user/driver_site.html
{% extends "user/home.html" %}

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message.message }}</li>
    {% endfor %}
  </ul>
{% endif %}




{% block content %}
    <h2>Your Task</h2>
    {% for driver in drivers %}
        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ driver.ride.destination }} // </a>
                <small class="text-muted">arrive at {{ driver.ride.arrival_time }} // </small>
                <small class="text-muted">{{ driver.ride.passenger_number }} Passengers // </small>
                <small class="text-muted">vehicle type is {{ driver.ride.vehicle_type }}</small>
            </div>
            
            
            <h2>Sharer</h2>
            {% for pa in driver.ride.sharer.all %}
                <a class="article-content">{{ pa.username }} // </a>
            {% endfor %}
            <h2>Special_Request</h2>
            <p class="article-content">{{ driver.ride.special_request }}</p>
            </div>
            {% if driver.ride.status == 'confirmed' %}
                <h2><a class="article-title" href="/driver_complete/{{driver.ride.id}}/", type = submit>Complete</a></h2>
            {% else %}
                <h2>Finish</h2>
            {% endif %}
        </article>
    {% endfor %}
{%endblock content%}

docker-deploy/web-app/user/templates/user/edit_request.html
{% extends "user/home.html" %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Edit Request </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a style="color:white" class="btn btn-secondary btn-xs" href="{% url 'home' %}">return</a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

docker-deploy/web-app/user/templates/user/index.html
{% extends "user/home.html" %}

{%block content%}

{% if message %}
<div style="text-align: center; padding: 50px 0;">
  <p><strong>{{ message }}</strong></p>
</div>
<div style="text-align: center;">
  <a style="color:white" class="btn btn-success btn-xs text-center"
                  href="{% url 'home' %}">Go to Home Page</a>
</div>
{% endif %}


{%endblock%}

docker-deploy/web-app/user/templates/user/register.html
{% extends "user/home.html" %}




{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> Join Today </h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                {% csrf_token %}

                {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red">{{ field.errors.0 }}</span>
                </div>
                {% endfor %}
                <div class="form-group">
                    <button class="btn btn-success btn-xs" type="submit">Create Your Account</button>
                </div>
            </form>
        </div>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
</div>

{% endblock %}

docker-deploy/web-app/user/templates/user/request_detail.html
{% extends "user/home.html" %}

{% block content %}

<div class="container my-5">
  <div class="d-flex justify-content-center">
    <div class="card" style="width: 50%">
      <div class="card-header bg-secondary text-white text-center">
        <h3 class="m-0">Order Detail</h3>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-between mb-3">
          <p><strong>Destination:</strong> {{ ride.destination }}</p>
          <p><strong>Arrival Time:</strong> {{ ride.arrival_time }}</p>
        </div>
        <p><strong>Owner:</strong> {{ ride.owner }}</p>
        <p><strong>Total Passenger Number:</strong> {{ ride.passenger_number }}</p>
        {% if ride.special_vehicle_type != None %}
          <p><strong>Special Vehicle Required:</strong> {{ ride.get_special_vehicle_type_display }}</p>
        {% endif %}
        <p><strong>Sharers:</strong></p>
        <ul>
          {% for value in ride.sharer.all %}
            <li>{{ value }}</li>
          {% endfor %}
        </ul>
        {% if ride.status == "Confirmed" %}
          <p><strong>Driver:</strong> {{ ride.driver }}</p>
          {% comment %} <p><strong>Driver Vehicle Type:</strong> {{ ride.driver.driver.field_of_Driver.get_vehicle_type_display }}</p> {% endcomment %}
       {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

docker-deploy/web-app/user/templates/user/search_ride.html
{% extends "user/home.html" %}

{% block content %}

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header bg-secondary text-white text-center">
            <h3 class="card-title"> Search Ride </h3>
          </div>
          <div class="card-body">
            <form method="post" novalidate>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  <label class="text-secondary">{{ field.label }}</label>
                  {{ field }}
                  <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
              {% endfor %}
              <button type="submit" class="btn btn-success mt-3">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

docker-deploy/web-app/user/templates/user/start_request.html
{% extends "user/home.html" %}

{% block content %}

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header bg-secondary text-white text-center">
            <h3 class="card-title"> Start a New Request </h3>
          </div>
          <div class="card-body">
            <form method="post" novalidate>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  <label class="text-secondary">{{ field.label }}</label>
                  {{ field }}
                  <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
              {% endfor %}
              <button type="submit" class="btn btn-success mt-3">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

docker-deploy/web-app/user/templates/user/test.html
{% extends "user/home.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <style>
      .table {
        background-color: #fff;
        color: #676a6c;
        border-radius: 0.375rem;
        box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
        table-layout: fixed;
        width: 100%;
      }

      .table th,
      .table td {
        padding: 0.75rem;
        vertical-align: top;
        border-top: 1px solid #dee2e6;
      }

      .table thead th {
        background-color: #f8f9fa;
        color: #212529;
        border-color: #dee2e6;
        text-align: left;
      }

      .table tbody + tbody {
        border-top: 2px solid #dee2e6;
      }

      .table .table {
        background-color: #fff;
      }

      .btn-primary {
        color: #fff;
        background-color: #212529;
        border-color: #212529;
      }

      .btn-primary:hover {
        color: #fff;
        background-color: #171919;
        border-color: #171919;
      }
    </style>
    <title>Rides Information</title>
  </head>
  <body>
    <div class="container my-5">
      <h1 class="text-left" style="font-size: 24px;">Rides Information</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Destination</th>
            <th>Arrival Time</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>San Francisco</td>
            <td>10:00 AM</td>
            <td>Active</td>
            <td>
              <button type="button" class="btn btn-primary mr-2">
                View Details
              </button>
              <button type="button" class="btn btn-secondary mr-2">


{% endblock %}